### ISSUE TITLE
evtl fehler

### ISSUE THREAD

**Issue by Necktschnagge** [hmfrank/Bigint#1]
Zeile 191 operator Plus

Du erstellst ein neues BigInt Objekt "copy" und setzt es gleich x
Dann addierst du x dazu, sodass 2*x herauskommt

Oder lese ich das falsch?

operator - müsste bei einer beliebigen Subtraktion immer ein BigInt 0 zurückgeben 🗡

**Comment by hmfrank** [comment]
Stimmt. Danke für den Hinweis. Ich wollte eigentlich `*this` kopieren.
